/* Generated By:JavaCC: Do not edit this line. calc_enterosConstants.java */
package traductor;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface calc_enterosConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LETTER = 6;
  /** RegularExpression Id. */
  int DIGIT = 7;
  /** RegularExpression Id. */
  int tNUM = 8;
  /** RegularExpression Id. */
  int tCONST = 9;
  /** RegularExpression Id. */
  int tVAR = 10;
  /** RegularExpression Id. */
  int tWRITE = 11;
  /** RegularExpression Id. */
  int tASS = 12;
  /** RegularExpression Id. */
  int tID = 13;
  /** RegularExpression Id. */
  int tPC = 14;
  /** RegularExpression Id. */
  int tMAS = 15;
  /** RegularExpression Id. */
  int tMENOS = 16;
  /** RegularExpression Id. */
  int tPROD = 17;
  /** RegularExpression Id. */
  int tDIV = 18;
  /** RegularExpression Id. */
  int tAP = 19;
  /** RegularExpression Id. */
  int tCP = 20;
  /** RegularExpression Id. */
  int tBASURA = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<LETTER>",
    "<DIGIT>",
    "<tNUM>",
    "\"const\"",
    "\"var\"",
    "\"escribir\"",
    "\"=\"",
    "<tID>",
    "\";\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "<tBASURA>",
  };

}
