/* Generated By:JavaCC: Do not edit this line. cpt.java */
package traductor;

//...

public class cpt implements cptConstants {
   //...

   public static void main(String[] args) {
           cpt parser = null;

           try {
                   if(args.length == 0) {
                           parser = new cpt(System.in);
                   }
                   else {
                           parser = new cpt(new java.io.FileInputStream(args[0]));
                   }
                   //Programa es el símbolo inicial de la gramática
                   parser.Programa();
                   //...
                   System.out.println("***** An\u00e1lisis terminado con \u00e9xito *****");
           }
           catch (java.io.FileNotFoundException e) {
                   System.err.println ("Fichero " + args[0] + " no encontrado.");
           }
           catch (TokenMgrError e) {

                   System.err.println("LEX_ERROR: " + e.getMessage());
           }
           catch (Exception e) {
                        // Handle the exception
                        System.err.println("An exception occurred: " + e.getMessage());
           }
        }

//------------ Símbolo inicial de la gramática. Para análisis léxico no hace falta más
  static final public void Programa() throws ParseException {
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tVAR:
        jj_consume_token(tVAR);
        break;
      case tDOSPUNTOS:
        jj_consume_token(tDOSPUNTOS);
        break;
      case tCOMA:
        jj_consume_token(tCOMA);
        break;
      case tARRAY:
        jj_consume_token(tARRAY);
        break;
      case tOFOP:
        jj_consume_token(tOFOP);
        break;
      case tSIZEOP:
        jj_consume_token(tSIZEOP);
        break;
      case tWHENOP:
        jj_consume_token(tWHENOP);
        break;
      case tDOOP:
        jj_consume_token(tDOOP);
        break;
      case tELSEWHENOP:
        jj_consume_token(tELSEWHENOP);
        break;
      case tELSEOP:
        jj_consume_token(tELSEOP);
        break;
      case tLOOPOP:
        jj_consume_token(tLOOPOP);
        break;
      case tDONE:
        jj_consume_token(tDONE);
        break;
      case tNULL:
        jj_consume_token(tNULL);
        break;
      case tABRE_PARENTESIS:
        jj_consume_token(tABRE_PARENTESIS);
        break;
      case tCIERRA_PARENTESIS:
        jj_consume_token(tCIERRA_PARENTESIS);
        break;
      case tPROCESO:
        jj_consume_token(tPROCESO);
        break;
      case tFUNCION:
        jj_consume_token(tFUNCION);
        break;
      case tIS:
        jj_consume_token(tIS);
        break;
      case tOUT:
        jj_consume_token(tOUT);
        break;
      case tIN:
        jj_consume_token(tIN);
        break;
      case tINOUT:
        jj_consume_token(tINOUT);
        break;
      case tRETURN:
        jj_consume_token(tRETURN);
        break;
      case tREAD:
        jj_consume_token(tREAD);
        break;
      case tREADLN:
        jj_consume_token(tREADLN);
        break;
      case tPRINT:
        jj_consume_token(tPRINT);
        break;
      case tPRINTLN:
        jj_consume_token(tPRINTLN);
        break;
      case tINT_TO_CHAR:
        jj_consume_token(tINT_TO_CHAR);
        break;
      case tCHAR_TO_INT:
        jj_consume_token(tCHAR_TO_INT);
        break;
      case tPUNTO_COMA:
        jj_consume_token(tPUNTO_COMA);
        break;
      case tASIGNADOR:
        jj_consume_token(tASIGNADOR);
        break;
      case tESCALAR:
        jj_consume_token(tESCALAR);
        break;
      case tLITERAL_NUMERO:
        jj_consume_token(tLITERAL_NUMERO);
        break;
      case tLITERAL_CARACTER:
        jj_consume_token(tLITERAL_CARACTER);
        break;
      case tLITERAL_BOOLEANO:
        jj_consume_token(tLITERAL_BOOLEANO);
        break;
      case tIDENT:
        jj_consume_token(tIDENT);
        break;
      case tTERMINAR:
        jj_consume_token(tTERMINAR);
        break;
      case tOPERADOR_ARITMETICO:
        jj_consume_token(tOPERADOR_ARITMETICO);
        break;
      case tOPERADOR_BOOLEANO:
        jj_consume_token(tOPERADOR_BOOLEANO);
        break;
      case tOPERADOR_RELACIONAL:
        jj_consume_token(tOPERADOR_RELACIONAL);
        break;
      case tSTRING:
        jj_consume_token(tSTRING);
        break;
      default:
        jj_la1[0] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tVAR:
      case tCOMA:
      case tDOSPUNTOS:
      case tARRAY:
      case tOFOP:
      case tSIZEOP:
      case tWHENOP:
      case tDOOP:
      case tELSEWHENOP:
      case tELSEOP:
      case tLOOPOP:
      case tDONE:
      case tNULL:
      case tABRE_PARENTESIS:
      case tCIERRA_PARENTESIS:
      case tPROCESO:
      case tFUNCION:
      case tIS:
      case tOUT:
      case tIN:
      case tINOUT:
      case tRETURN:
      case tREAD:
      case tREADLN:
      case tPRINT:
      case tPRINTLN:
      case tINT_TO_CHAR:
      case tCHAR_TO_INT:
      case tPUNTO_COMA:
      case tASIGNADOR:
      case tESCALAR:
      case tLITERAL_NUMERO:
      case tLITERAL_CARACTER:
      case tLITERAL_BOOLEANO:
      case tTERMINAR:
      case tOPERADOR_ARITMETICO:
      case tOPERADOR_BOOLEANO:
      case tOPERADOR_RELACIONAL:
      case tIDENT:
      case tSTRING:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_1;
      }
    }
    jj_consume_token(0);
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public cptTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[2];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0xffffff00,0xffffff00,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x87fff,0x87fff,};
   }

  /** Constructor with InputStream. */
  public cpt(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public cpt(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new cptTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public cpt(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new cptTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public cpt(cptTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(cptTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List jj_expentries = new java.util.ArrayList();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[55];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 2; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 55; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

}
