/* Generated By:JavaCC: Do not edit this line. cptConstants.java */
package traductor;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface cptConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LETTER = 1;
  /** RegularExpression Id. */
  int DIGIT = 2;
  /** RegularExpression Id. */
  int tCOMENTARIO = 3;
  /** RegularExpression Id. */
  int tVAR = 8;
  /** RegularExpression Id. */
  int tCOMA = 9;
  /** RegularExpression Id. */
  int tDOSPUNTOS = 10;
  /** RegularExpression Id. */
  int tARRAY = 11;
  /** RegularExpression Id. */
  int tOFOP = 12;
  /** RegularExpression Id. */
  int tSIZEOP = 13;
  /** RegularExpression Id. */
  int tWHENOP = 14;
  /** RegularExpression Id. */
  int tDOOP = 15;
  /** RegularExpression Id. */
  int tELSEWHENOP = 16;
  /** RegularExpression Id. */
  int tELSEOP = 17;
  /** RegularExpression Id. */
  int tLOOPOP = 18;
  /** RegularExpression Id. */
  int tDONE = 19;
  /** RegularExpression Id. */
  int tNULL = 20;
  /** RegularExpression Id. */
  int tABRE_PARENTESIS = 21;
  /** RegularExpression Id. */
  int tCIERRA_PARENTESIS = 22;
  /** RegularExpression Id. */
  int tABRE_CORCHETE = 23;
  /** RegularExpression Id. */
  int tCIERRA_CORCHETE = 24;
  /** RegularExpression Id. */
  int tPROCEDIMIENTO = 25;
  /** RegularExpression Id. */
  int tFUNCION = 26;
  /** RegularExpression Id. */
  int tIS = 27;
  /** RegularExpression Id. */
  int tOUT = 28;
  /** RegularExpression Id. */
  int tIN = 29;
  /** RegularExpression Id. */
  int tINOUT = 30;
  /** RegularExpression Id. */
  int tRETURN = 31;
  /** RegularExpression Id. */
  int tREAD = 32;
  /** RegularExpression Id. */
  int tREADLN = 33;
  /** RegularExpression Id. */
  int tPRINT = 34;
  /** RegularExpression Id. */
  int tPRINTLN = 35;
  /** RegularExpression Id. */
  int tINT_TO_CHAR = 36;
  /** RegularExpression Id. */
  int tCHAR_TO_INT = 37;
  /** RegularExpression Id. */
  int tPUNTO_COMA = 38;
  /** RegularExpression Id. */
  int tASIGNADOR = 39;
  /** RegularExpression Id. */
  int tESCALAR = 40;
  /** RegularExpression Id. */
  int tLITERAL_NUMERO = 41;
  /** RegularExpression Id. */
  int tLITERAL_CARACTER = 42;
  /** RegularExpression Id. */
  int tLITERAL_BOOLEANO = 43;
  /** RegularExpression Id. */
  int tTERMINAR = 44;
  /** RegularExpression Id. */
  int tOPERADOR_ARITMETICO_SUMATIVO = 45;
  /** RegularExpression Id. */
  int tOPERADOR_MULTIPLICATIVO = 46;
  /** RegularExpression Id. */
  int tOPERADOR_BOOLEANO = 47;
  /** RegularExpression Id. */
  int tNOT = 48;
  /** RegularExpression Id. */
  int tOPERADOR_RELACIONAL = 49;
  /** RegularExpression Id. */
  int tFLECHA = 50;
  /** RegularExpression Id. */
  int tIDENT = 51;
  /** RegularExpression Id. */
  int tABRE_COMILLA = 52;
  /** RegularExpression Id. */
  int noReconocido = 53;
  /** RegularExpression Id. */
  int tTEXTO_STRING = 54;
  /** RegularExpression Id. */
  int tDOBLE_COMILLA = 55;
  /** RegularExpression Id. */
  int tLITERAL_STRING = 56;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int ENTRE_COMILLAS = 1;
  /** Lexical state. */
  int ERROR = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<LETTER>",
    "<DIGIT>",
    "<tCOMENTARIO>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"var\"",
    "<tCOMA>",
    "<tDOSPUNTOS>",
    "\"array\"",
    "\"of\"",
    "\"size\"",
    "\"when\"",
    "\"do\"",
    "\"elsewhen\"",
    "\"else\"",
    "<tLOOPOP>",
    "\"done\"",
    "\"null\"",
    "<tABRE_PARENTESIS>",
    "<tCIERRA_PARENTESIS>",
    "<tABRE_CORCHETE>",
    "<tCIERRA_CORCHETE>",
    "\"proc\"",
    "\"func\"",
    "\"is\"",
    "\"out\"",
    "\"in\"",
    "\"inout\"",
    "\"return\"",
    "\"read\"",
    "\"readln\"",
    "\"print\"",
    "\"println\"",
    "\"int2char\"",
    "\"char2int\"",
    "<tPUNTO_COMA>",
    "<tASIGNADOR>",
    "<tESCALAR>",
    "<tLITERAL_NUMERO>",
    "<tLITERAL_CARACTER>",
    "<tLITERAL_BOOLEANO>",
    "\"EXIT\"",
    "<tOPERADOR_ARITMETICO_SUMATIVO>",
    "<tOPERADOR_MULTIPLICATIVO>",
    "<tOPERADOR_BOOLEANO>",
    "\"not\"",
    "<tOPERADOR_RELACIONAL>",
    "\"->\"",
    "<tIDENT>",
    "\"\\\"\"",
    "<noReconocido>",
    "<tTEXTO_STRING>",
    "\"\\\"\\\"\"",
    "<tLITERAL_STRING>",
    "\"--\"",
    "<token of kind 58>",
    "<token of kind 59>",
  };

}
